site_name: Google ADK Extras
site_description: Production-ready services, credentials, and FastAPI wiring for Google ADK
site_url: https://deadmeme5441.github.io/google-adk-extras/
repo_url: https://github.com/DeadMeme5441/google-adk-extras
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Quickstarts: quickstarts.md
  - FastAPI Integration: fastapi.md
  - Services:
      - Durable Services: services.md
      - Credentials: credentials.md
  - Programmatic Agents: agent-loading.md
  - URIs & Configuration: uris.md
  - Examples: examples.md
  - Troubleshooting: troubleshooting.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
docs_dir: docs
