name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup uv
      uses: astral-sh/setup-uv@v4

    - name: Install test extras
      run: |
        uv sync
        uv pip install -e '.[all,dev]'

    - name: Run tests
      run: |
        uv run pytest tests/ -v

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Setup uv
      uses: astral-sh/setup-uv@v4

    - name: Install lint deps
      run: |
        uv sync
        uv pip install -e '.[dev]'

    - name: Run linting
      run: |
        # Add linting commands here if you have any
        echo "No linting configured"
