name: Build and Deploy Docs

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies (via uv)
        run: |
          uv pip install --system mkdocs-material mkdocstrings[python]
          # Install the package so mkdocstrings can import modules
          uv pip install --system -e .

      - name: Build and deploy (via uv)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run mkdocs gh-deploy --force
