name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for PyPI Trusted Publisher (optional)
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Build distributions
        run: |
          uv build --no-sources
          ls -la dist
      - name: Publish to PyPI via uv (Trusted Publisher)
        if: success()
        run: uv publish
        env:
          # For token-based publishing instead of Trusted Publisher, use:
          # UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          # and optionally disable id-token permission above
          UV_NO_PROGRESS: 1
