name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv (with cache)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python (per pyproject constraints)
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Ensure Python installed for uv
        run: uv python install

      - name: Build distributions
        run: uv build

      - name: Publish to PyPI (Trusted Publishing)
        env:
          GITHUB_ACTIONS: true
        run: uv publish
